{{- if and .Values.server.enabled .Values.server.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "jwks-service.server.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "jwks-service.server.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.server.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "jwks-service.server.selectorLabels" . | nindent 6 }}
{{- end }}
